allowBuilds:
  '@clerk/shared': false
  '@parcel/watcher': false
  '@percy/core': false
  esbuild: false
  onnxruntime-node: false
  protobufjs: false
  sharp: false
  unrs-resolver: false
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@percy/core'
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp
  - unrs-resolver
